project:
  type: website

website:
  title: "Techne"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Staff"
        href: staff.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Demo Day"
        href: demo_day.qmd
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



