---
title: "Procedures for Demo Day"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

These are the procedures we follow on "Demo Day" during which students present their projects to an audience of their peers and guests. Demo Day is public. All are welcome. To attend, you need the Zoom link. 

The document begins with an overview of the procedures and then provides advice to guests, students and teaching fellows. If you are a guest, you do not need to read the advice for students and TFs.

Key request to everyone: ASK LOTS OF QUESTIONS!

## Overview

Each breakout room will include two students and various guests, both course staff and visitors. 

Basic idea is that all students are in two groups: A and B. Students in Group A present first. We will post the assignments.

At the start, we are all in the main room. I offer introductions. I open the breakout rooms. Students go to their assigned rooms. (Guests will also go to the room featuring the student they want to listen to.) Chat politely. I will then issue a Breakout Room message saying to start. The A student presents her work for 4 minutes. The B student asks a lot of questions. So do the guests. 

After three and a half minutes, I send a Message saying: 30 seconds left. At four minutes, I Message “Switch Rooms!”

Please switch rooms when I ask you to!

Student A stays in the room. Student B moves one room up. From room 6 to room 7, for example. (If you are the B student in the highest room, you move to room 1.) Then, Student A presents again.

After 30 minutes of this, the A students will have presented 5 or 6 times. Good stuff! I bring back everyone to the main room. Say a few words. And then we do the whole thing again, with students again starting in the same rooms as in the first round, but, this time, with the B students presenting and staying put in the rooms. And now the A students move from room to room.

After the B students present, I close the breakout rooms, thereby bringing everyone back together. I offer thanks and congratulations.

## Advice for Guests

You need three things: a Zoom link for Demo Day, the breakout room number in which your student is presenting, and whether she is in Group A (presenting first) or Group B (presenting second). 

But please be flexible! We sometimes need a student to switch breakout rooms and/or switch from Group A to B. In Zoom, you should be able to see all the rooms (and who is in them) if you are having trouble finding your student.

If your student is in Group A, please try to arrive on time. If she is in Group B, you can arrive at the start and watch other presentations. Or, you can show up at the class midpoint so that you just watch her presentations.

You can also leave early, once you have seen your student present. (Many parents and grandparents like to watch their student present more than once. This is encouraged.) You are also welcome to check out other student presentations. Just move to any other breakout room whenever you like.

Most importantly: ASK LOTS OF QUESTIONS!

## Advice for Students

The only material you need for your presentation is a browser which can show both your project's webpage and your Github repo. We don't use Powerpoint or other nonsense.

Planning is important. Make sure that your TF knows your plans. For example, if a family event prevents you from attending Demo Day, let your TF know as soon as possible. Otherwise, you make her planning much more difficult.

The delicate dance of Demo Day depends on everyone doing their part. You need to show up on time. Otherwise, things get very confusing. If a last-minute emergency arises, email your TF, the head TF and Preceptor as soon as you know that you won't be there.

In addition to presenting, you will also be attending presentations by several classmates. Be an engaged listener! Act toward them as you hope they will act toward you.

Most importantly: ASK LOTS OF QUESTIONS! 

### When Presenting

Have fun! Demo Day is a joyful occasion. Your (natural) nervousness is unwarranted. Everyone wants you to succeed. Share your screen the entire time. Always start on your home page. Give your opening paragraph. Pause to see if anyone has any questions. If they don't, spend another paragraph explaining the details of your main graphic. Pause again. Questions are fun, but you have to give people a chance to ask them.

When pausing, use the "Take a sip of water" technique. Stop talking. Imagine that you are reaching for a class of water, lifting it up, taking a sip, and putting it back down. Only after that can you assume that there are no questions.

Sadly, you will sometimes be stuck with an audience too shy to ask questions. That is OK! One of the things you are learning in this class is how to handle different sorts of audiences. To handle a shy audience, you need to have prepared ahead of time 5 minutes worth of things to talk about. This can, and should, include a tour of your Github repository,

### When Listening

Always allow the student you are listening to to give their opening paragraph, perhaps even allowing them a second paragraph to explain their plot. But then interrupt them and ask a question. It doesn't really matter what the question is. The important thing is to get a conversation going, to demonstrate to other visitors that questions are welcome and that they should ask some as well.

Check out the spreadsheet to see which student presentations you are likely to attend. Check out the webpages and Github repos ahead of time. Learn a little bit about the topics. The more you prepare, the better an audience you will be.


## Advice for Teaching Fellows

First, two TFs are paired together and given a continuous set of breakout rooms, say 21 to 28. The two TFs should, obviously, coordinate ahead of time. They need one room for every two students so, in this case, with 8 rooms, they can't have more than 16 students between them. 

Second, the two TFs divide the students into two equal groups: A and B. If possible, all the students for one TF are in A and all the students for the other TF are in B. But, if the TFs are responsible for different numbers of students, this might not be possible. However, we try to keep students from the same TF together in the same Group as much as possible.

The key is that these two TFs and their students form a self-contained Demo Day ecosystem. They don't care what is going on in other breakout rooms. Other breakout rooms don't care about what is happening with them. This ensures that Demo Day can continue even if some groups get messed up.

At this point, all students, regardless of TF, have been assigned to either A or B. Each breakout room has two "starting" students, an A and a B. Group A presents first.  

If a TF pairing features an odd number of students, then one of the TFs pretends to be a student so that there is always someone listening to a student's presentation. Annoyingly, this often occurs at the last minute when a student fails to show. So, at the start, TFs need to pay attention and be nimble.

If there are an odd number of students, it is best if the extra student is placed in Group A and in the last room in your suite of rooms. That is, you have an extra presenter in the first round. Again, you might need to do this at the after Demo Day has started and you notice that a student is missing. In that case, you will often have to tell a student that she is now in Group A instead of Group B and should present first. One of the TFs then replaces the missing student by being a fake Group B "student" who just moves from room to room, listening to presentations in the first round. In the second round, this TF does not need to pretend any longer. She does not present, obviously. Instead, the room that she was in is eliminated from the cycle. (Obviously, it is helpful if this is the highest room in the group.)

The Group A student who was in that room is now moved one room up, to a different starting room. Of course, that room already has a Group A student in it. And that is OK! There is nothing wrong with having two Group A students moving from room-to-room, listening to a different Group B student each time. The key point is that a breakout room which was used in the first session is no longer in use. You need to ensure that Group A students know to skip that room.

If Group A and Group B are balanced or, in the case of imbalance, we are in the second session, then you are free to move around. See as many presentations as you can, even if you can't stay for any individual presentation from start to finish. Students won't mind if you arrive late or leave early. They know that you have a lot of rooms to worry about. But they always appreciate it if you can see at least some of their presentation.

Whenever you visit a room, make sure that questions are being asked. The best way to do that is to ask a question yourself! You can also interrupt and tell the audience student to ask a question. Anything which gets the conversation going is a good idea.

Even when you are visiting rooms, you (and/or your partner) need to keep an eye on all your other rooms, especially when we transition. Too often, a student will delay moving from room N to N+1. The reason for this delay is generally innocuous. They are just honestly intererested in the presentation! They have more questions!

Doesn't matter! Delays are bad. First, they prevent the student in the current room from starting their next presentation. After all, a new student has just entered the room. Making her wait is rude. Even worse, the presenting student in room N+1 is sitting their alone, waiting. She doesn't know what is happening. Why has no one come to her room? Delay is unfair to her as well.

## Advice for the Head TF

The key is to figure out, as early in the class as possible, which TFs are responsible for which students. The sooner you have a good mapping of TFs-to-students, the easier everything is. Of course, you have to deal with students dropping the class and, sometimes, with TFs vanishing.

First, ask TFs if there is another TF who they want to partner with on Demo Day. The more that TFs work with other TFs whom they like, the better. If there are an odd number of TFs, then one grouping with have three TFs.

Second, clarify just how many students these two TFs have. That determines how many rooms they need to be assigned. If there is some uncertainty, assign this pair an extra room or two. The worst case is that those rooms remain unused.

Third, set up the first draft of a public spreadsheet which specifies which block of rooms each TF pair is responsible for and which students are assigned to which rooms. Ask TFs to review the spreadsheet. Require students to find themselves in the spreadsheet and then post their room assignment to the #class-work channel. Also, require students to add "Confirmed" to the column next to their room assignments. (As always, make spreadsheets which never have more than one student in a given row.)





