---
title: "Final Projects"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

A total of 184 students have completed previous versions of this class. Congratulations! 

## August 2025

[Alfred Cheung](https://github.com/AlfredCheung2121): [Flight Price Prediction](https://alfredcheung2121.github.io/Flight-Price-Prediction/). Flight prices increase with the number of stops, with a strong positive correlation of 0.621  

[Luke Li](https://github.com/lukearoni/financial-literacy): [Credit Card Payment Behavior](https://lukearoni.github.io/financial-literacy/). For every 1 point increase in a standardized financial knowledge test score, the log odds of someone paying off a credit card bill increases by 0.047, and the 95% confidence interval for this estimate ranges from -0.005 to 0.098.  

[Eric Butte](https://github.com/ebutte18): [Goal Scoring in Hockey](https://ebutte18.github.io/hockey-goals/). For the hockey player Sam Reinhart, each additional foot away from the net he attempted a shot, the log-odds of scoring a goal decreased by 0.033, with a 95% confidence interval from -0.045 to -0.022.  

[Rishith Bethina](https://github.com/Rishibethina): [Restaurant thriving analysis](https://rishibethina.github.io/restaurant-analysis-clean/). This analysis reveals that delivery capability became 192% more important for restaurant success during COVID-19 (coefficient increasing from 0.12 to 0.35), while price sensitivity intensified by 88%, demonstrating that operational flexibility.  

[Surya Fraser](https://github.com/sfraser8910): [Internet Access in the US](https://sfraser8910.github.io/us_internet_access/). While increases in income were associated with only a small increase in the log-odds of internet access, one year increases in age were associated with a 0.0339 decreased log-odds of internet access with a 95% confidence interval of -0.0341 to -0.0338.  

[Jacob Khaykin](https://github.com/JacobKhay): [AI Jobs Weighting Analysis](https://jacobkhay.github.io/AI-Share-Replication-Differences/). Weighting by log-population reveals that labor market tightness, not education, is the most consistent driver of AI job adoption across different county sizes.  

[Hassan Ali](https://github.com/alisoni007/): [Greenhouse gas emission](https://alisoni007.github.io/chem-ghg-electronics/). The analysis identified the predominant chemical species and highlighted significant facility-level and temporal trends in the industry by focusing on reported emissions in metric tons. A limited number of chemicals contribute disproportionately to total emissions, as indicated by exploratory data analysis, whereas annual patterns reveal variability associated with facility operations and manufacturing cycles.  

[Ansh Patel](https://github.com/brunchmaster-ap): [Global Commodity Trade`](https://brunchmaster-ap.github.io/Global-Commodity-Trade/). Following the 2008 financial crisis, U.S. live animal imports dropped by over 25% between 2008 and 2010, and remained on average 15% lower in the years after, indicating a lasting shift in agricultural trade behavior.  

[Faran Abbas](https://github.com/faranabbas-repo): [Global Economic Growth Analysis (2000–2023)](https://faranabbas-repo.github.io/global-economic-growth-analysis/). Investment is the single most powerful driver of economic growth, with each percentage point increase in gross capital formation (as % of GDP) associated with 0.2-0.3 percentage points higher GDP growth, making it the key policy lever for sustainable development.  

[Naveed Ahmad](https://github.com/naveedgill4u): [Income Inequality in U.S](https://naveedgill4u.github.io/income-inequality-county-wise/). The income inequality (Gini Index) in U.S is predicted to be 0.48, with a 95% confidence interval of 0.46 to 0.5 in most of the counties.  

[Ayush Chandra](https://github.com/SmartSilver5294): [EV vs Gas Costs over 3 Years](https://smartsilver5294.github.io/ev-vs-gas-costs/). The best EV model compared to its gas counterpart is the Honda Prologue, and the best states to buy an EV in are Washington and California, which saves approximately $3,850 in Washington.  

[Jack Xu](https://github.com/jackxu3): [The Effects of Wildfires on Bird Migration Routes](https://jackxu3.github.io/fires-and-birds/). For each one-degree counterclockwise increase in direction relative to the east, the model predicts that the distance to the nearest wildfire decreases by approximately 0.059 units with a 95% confidence interval ranging from -0.096 to -0.021.  

[Adit Rohit](https://github.com/aditrohit): [California Housing](https://aditrohit.github.io/California-Housing/). This project explores California’s housing market using a cleaned dataset containing neighborhood-level statistics on income, home values, and geographic location.  

[Uma Ravat](https://github.com/uravat): [Relationship between food consumed and body mass index (bmi)](https://uravat.github.io/bmi-nutrition/). I examine the relationship between food consumed and body mass index.  

[Paramanyu Gupta](https://github.com/Paramanyu2010): [Music Performance Analytics](https://paramanyu2010.github.io/music_skill_analysis/). The model predicts that for every additional 30 minutes of daily practice, a musician's performance score increases by approximately 5% with confidence intervals from 3.5% to 6.5%, with this effect being consistent across all instruments examined.  

[Neelam Arshad](https://github.com/NeelamArshad): [US Traffic Accidents Analysis](https://neelamarshad.github.io/us-traffic-accidents/). This analysis reveals that daily human activity, traffic density, and weather conditions (snow with 1.2% more chances of accidents and heavy rain likely cause 3% greater number of accidents) play a significant role in determining the severity and when accidents are most likely to occur in the U.S.  

[Sophia Yao](https://github.com/sophiay14): [Titanic Survival](https://sophiay14.github.io/titanic-survival/). During the sinking of the Titanic, men had survival odds reduced by nearly 91% (95% confidence interval: 87%–95%), third-class passengers by 91% (95% confidence interval: 84%–95%), and each additional year of age lowered survival odds by about 3% (95% confidence interval : 2%–5%).  

[Faisal Jan](https://github.com/FaisaljanBaloch): [LEP on Income](https://faisaljanbaloch.github.io/lep-on-income/). Across all education levels, males earn 20–50% more than females, with the largest gender and language-based income gaps appearing at the graduate level where English Proficient males earn over $70,000, nearly 50% more than their female counterparts.  

[Inam Khan](https://github.com/inammarwat): [Predicting Life Expectany](https://inammarwat.github.io/predicting-life-expectancy/). A country’s income and resource capacity has the strongest impact on life expectancy—each 0.1-point increase predicts 1.1 additional years of life, outweighing health risks like HIV prevalence.  

[Shuntaro Kawakami](https://github.com/skawakamNY/bitcoin_analysis): [Bitcoin Price Trend Analysis](https://skawakamny.github.io/bitcoin_analysis/). Dow Jones Index exhibited a strong positive association (p < 0.001) where increases in stock market performance correlate with higher bitcoin prices and the 10-Year Treasury Yield Granger-causes Bitcoin price (p = 0.032), suggesting it has a statistically significant temporal influence on Bitcoin price.  

[Sharjeel Jamal](https://github.com/Sharjeel46): [Predicting Chess outcome by recognizing moves patterns](https://sharjeel46.github.io/Predicting-Chess--outcome/). Using logistic regression on a dataset of 170,500 games, the model was able to predict win or loss outcomes with 86% accuracy.  

[Sajida Rehman](https://github.com/Sajida25): [Teen Smartphone Usage and Addiction](https://sajida25.github.io/predicting-phone-addiction/). Each additional hour spent on the phone increases the odds of addiction by approximately three times, whereas an extra hour of sleep lowers those odds by about 44%.  

[Jishnu Veerapaneni](https://github.com/jishnuvee): [Predicting Psychiatric Disorders](https://jishnuvee.github.io/Psychiatric-diagnosis/). Bipolar disorder, panic disorder, social anxiety disorder, and schizophrenia all show significantly increased left temporal (F7) delta power, with bipolar disorder demonstrating the strongest effect at 0.080 units (95% CI: 0.018 to 0.143), suggesting that left-hemisphere temporal abnormalities could potentially aid in early detection and diagnosis of these specific psychiatric conditions, though the wide confidence intervals indicate substantial uncertainty in the true magnitude of these neurological signatures.  

[Abdul Hannan](https://github.com/Abdul-Hannan96/online-shopping): [Online Shopping Behavior](https://abdul-hannan96.github.io/online-shopping/). People who view more product pages are significantly more likely to make a purchase, highlighting the importance of keeping visitors engaged.  

[Umaira Nazar Hussain](https://github.com/umaira2022): [Digital Inequality in U.S. Broadband Access](https://umaira2022.github.io/Digital-Inequality-in-U.S/). A $1,000 rise in median income is linked to a 2.4% increase in broadband access—highlighting deep digital inequality across 3,000+ U.S. counties.  

## August 2024

[Alan Tao](https://github.com/alantao5056): [Spotify Songs](https://alienjao.quarto.pub/spotify-songs-v2/). 25 points in danceability is associated with 3 (+- 0.25) points of popularity on a 100 point scale. 

[Lela Sengupta](https://github.com/lelasengupta): [Analysis of Hidden Stock Orders](https://lelasengupta.quarto.pub/hidden-order/). Low volatility stocks experience about 48% of the hidden orders high volatility stocks experience, plus or minus 4%. 

[Gitanjali Sheth](https://github.com/gshethg): [Effect of physicochemical properties of wine on their quality](https://gshethg.quarto.pub/wineanalysis/). For each one-unit increase in alcohol content, the quality of the wine is expected to increase by 0.34 units, with a 95% CI of 0.31 to 0.37.  

[Tanay Janmanchi](https://github.com/tjanamnchi2): [2020 United States Presidential Election results by region.](https://tjanamnchi2.github.io/2020-election/). Given that a voter is from the South, there is a 52% chance that they will vote for Biden, although that number could be anywhere from 48% to 56%, despite being his least popular region. 

[Aditya Narayan](https://github.com/adi123soccer): [Different Factors Affect On Academic Performance](https://adi123soccer.quarto.pub/academic-vs-stress/). Increased stress is linked to poorer academic performance, with each additional unit of stress generally resulting in a decrease of about 1.4 units in academic performance, plus or minus 0.3 units.  

[Grant Quattlebaum](https://github.com/GrantQ9): [Quality of Magic: the Gathering Cards for Draft](https://grantq9.github.io/MTG-Draft-Card-Quality/). For rare Magic cards, a one mana higher cost is associated with a 0.55% increase in winning the game, give or take 0.25%.  

[SriRitvik Yellamilli](https://github.com/Pineapplespace789/average-wages): [Average Hourly Wages Yearly in the US](https://pineapplespace789.quarto.pub/wages-in-usa/). Men generally earn higher wages than women in all observed categories, with men averaging $15,000 and women averaging $12,000 per month, reflecting a significant gender wage gap.  

[Sophie Zhu](https://github.com/sophiezla): [Sepsis Survival Predictions](https://sophiezla.github.io/sepsis-survival-predictions/). A 60 year old female with 1 case of Sepsis is predicted to have a 95.86% chance of survival, though this may be between 95.25% to 96.41%. 

[Harshil Kurapati](https://github.com/hkurapat): [Income correlated to Race and Gender](https://hkurapat.quarto.pub/income-based-on-race-and-gender/). The analysis reveals that both race and gender significantly influence income levels, with disparities evident across different racial groups and between genders.  

[Anna Shao](https://github.com/annashao12): [Health in the US](https://annashao12.quarto.pub/health-in-the-us/). Compared to individuals without children, individuals with one to three children showed a significant decrease in the likelihood of having a health condition.  

[Melody Liu](https://github.com/mliu-13): [Waste Recycled](https://mliu.quarto.pub/waste-recycled/). There seems to be a strong correlation between waste recycled and incinerated, mismanaged, and landfilled waste. 


[Elaine Zhang](https://github.com/elainez1006): [Maternal Mental Health on the Health of the Baby](https://elainez1006.github.io/pregnancy-data/). It is shown that mothers with a high Edinburgh Postnatal Depression Scale (EPDS) results have children weighing 0-8% less compared to the average weight of 3,463 grams.  

[Roshan Ranganathan](https://github.com/PhoenixRCheetah): [Formula 1 data analysis for the 2023 season](https://thematrix.quarto.pub/formula-1-data-analysis-for-the-2023-season/). Our analysis reveals that Max Verstappen, a driver for Red Bull, is statistically the best driver in the 2023 Formula 1 season.  

[Mihir Kaushal](https://github.com/MihirKaushal): [Effect of Drugs on Memory Recall.](https://mihirkaushal.github.io/drug-memory-test/). One of the drugs has a negative impact on memory recall.  

[Akhil Bellamkonda](https://github.com/akhilbelllamkonda): [Mesa Arrests](https://abellamkonda.quarto.pub/akhil-bellamkonda/). Our analysis shows that males are statistically more likely to be arrested than females, with a predicted arrest probability that is 15% higher on average.  

[Wallstreet Petrus-Nihi](https://github.com/Wallstreet111): [Heart Disease Prediction by Age and Gender](https://wpetrus.quarto.pub/heart-disease-prediction-by-age-and-gender). This project examines how variations in age and gender affect heart disease risk, aiming to develop a predictive model that enhances health assessments.  

[Lowell Ethan Xavier](https://github.com/LowellEthan): [Lung Cancer Prediction](https://lowellethan.github.io/Lung-Cancer-Prediction/). A person who is exposed to a lot of air pollution is at a greater risk for lung cancer than a heavy smoker, with an estimated difference in their impacts being 0.11(± 0.04) on an 8 point scale.  

[Ronit Dash](https://github.com/DashRon25): [What Crimes Would Most Likely Find A Culprit in England?](https://dashr.quarto.pub/england-crime-analysis/). This project analyzes the types of crimes that find a culprit, finding that despite total conviction rates being low in England,  Burglary and Theft Crimes have the highest rate with 3.06% and 2.87% on average respectively.  

[Tanish Thaker](https://github.com/Tanish-Thaker): [OW2 Win Rates](https://tanish-thaker.quarto.pub/ow2-win-rate-predictions/). Based on the collected data, the win rates of players tend to be the highest when their statistics for each variable is at the 60-80 percentile of that variables spectrum.  

[Areeb Atif](https://github.com/AreebAtif1): [BMI and Diabetes](https://areeb-atif.quarto.pub/bmi-and-diabetes/). BMI is correlated with the risk of diabetes  

[Aaditya Gupta](https://github.com/AadityaG2011): [Math, Reading, and Writing Exam Scores by Parental Education Level, Gender, and Test Preparation](https://aadityag2011.quarto.pub/exam-performance-project/). On average, male students do 8% better than female students on math exams, plus or minus 3%.  

[Bingbing Luo](https://github.com/blstudystudy): [Environment impact by food](https://blstudystudy.quarto.pub/environment_impact_food/). Modeling the relationships between types of food and negative impact on the environment  

[Aedan Liao](https://github.com/aedan00/): [S&P 500 Correlation w/ US Presidents](https://aedan.quarto.pub/gspc-final-proj/). The stock market is affected by policies of certain presidential administrations  

[Annika Shivam](https://github.com/booleansarebinary): [What Makes a Book Popular?](https://booleansarebinary.quarto.pub/what-makes-a-book-popular/). Fiction books tend to sell, on average, around 600 more units than nonfiction books  

[Shyamali Sheth](https://github.com/Shyamali-Sheth): [student-GPA](https://shyamali.quarto.pub/student-gpa/). How different learning factors effect the GPA of a student.  

[Jason Fisher](https://github.com/jasonfisher0/finalproj): [Alzheimer's Diagnosis Prediction](https://github.com/jasonfisher0/AlzheimersDiagnosis). Physical function has a greater association with Alzheimer's diagnosis than mental function.  

[Rajeev Kumar yadav](https://github.com/Rajeev-ky): [Housing Prices](https://rajeev-ky.quarto.pub/housing-prices/). Preferred area housing prices are higher despite the furnishing status of the housing.  

[Hunter Stephens](huner1212 (Hunter Stephens) (github.com)): [Effect of Silver and Bronze Medals on Olympic Placing](https://hunter-stephens.quarto.pub/bronze-and-silver-medals-on-olympic-placing/). Silver medals have a much stronger effect on Placment than Bronze medals  

[Hao Lin](https://github.com/hlinca/wildfire_model): [Wildfire Model](https://hlinca.quarto.pub/wildfire_model/). Modeling the Impact of Environmental Conditions on Wildfire Incidents in California  

[Pragnyasri Sankar](https://github.com/PragnyaSankar7): [Indicators of Diabetes](https://pragnyasankar7.quarto.pub/diabetes-indication/analysis.html). This study uses factors including age, gender, BMI, and more to detetc within which conditions diabetes is more common.  

[Ali Atif](https://github.com/AliAtif09): [Olympic historical Model](https://ali-123.quarto.pub/olympic-historical-dataset/). This project predicts thetotal number of medals based on the number of gold, silver, and bronze medals.  

[Nithura Thevarajah](https://github.com/engineer-nithura): [Predicting Technological Evolution using Anthropology](https://nithura-t.quarto.pub/human-evol-analysis/). Precision in motor dexterity is a major contributor in the need for technological development compared to cranial capacity  

[Tulika Punia](https://github.com/puniat): [Correlation Between Education Level and Income](https://puniat.github.io/income/). Education levels may not influence income as significantly as commonly believed.  

[Judy Zhu](https://github.com/JudyZ2024): [How Chat-gpt Affects Global C02 Emissions](https://judy-zhu.quarto.pub/chat-gpt-co2/). Our new daily routine of using Chat-gpt releases over 50 gigawatt hours a year, and over 3% of global consumption, and are expected to double before 2030.  

[Dinesh Satyavolu](https://github.com/dsatyavolu): [New York City Bike Durations](https://dsatyavolu.quarto.pub/new-york-city-bike-durations/). On average, bike rides are shortest late in the day, and longest on Friday, with an approximate increase of 7.79 minutes compared to other days of the week.  

[Aleksandar Joksic](https://github.com/Alex212021/): [Income predictors](https://alex212021.quarto.pub/predicting-income/). Individuals with higher income tend to be White, male, more educated  

[Ivy Spratt](https://github.com/ivyspratt): [Depression vs Music Genre](https://ivyspratt.github.io/depression-music-effects/). Gospel music seems to decrease depression levels the most, and listeners of the genre are the happiest.  

[Aashna Patel](https://github.com/aashna-a-patel): [Cardiac Clues and Causes](https://aashna-a-patel.github.io/heart-attack/). This analysis uncovers critical factors influencing heart attack risk, providing valuable insights for improving prevention and treatment strategies.  

[Jacob Hardin-Bernhardt](https://github.com/jacobhb175): [Effects of Nuclear Proliferation on Peace](https://jacobhb175.github.io/nuclear-correlates/). The effects of nuclear proliferation as opposed to those of great power involvement on peace are negligible.  

[Rishith Ravi](https://github.com/rishithr19): [Acceptance of Personal Loans](https://36ee081b21194077b2dc70316c852d2f.publish.posit.cloud/). Customers with a higher income are 30% more likely to accept a personal loan compared to those with lower income.  


[Hans Zhang](https://github.com/hanszca): [Life by socio-economic](https://hanszca.quarto.pub/life_by_econ/). Life expectancy by socio-economic factors  

[Sharav Joshi](https://github.com/sharav12): [Difference in growth between hispanic and non-hispanic populations](https://sharav.quarto.pub/population-growth-analysis/). Both year and population group significantly influence growth trends, highlighting the dynamic demographic shifts within the U.S. population.  

[Zephan Shivam](https://github.com/PythonGoaler): [Three Key Takeaways from The Game of Golf](https://zshi.quarto.pub/three-golf-takeaways/). The difficulty of courses in the PGA are well balanced, driving the ball over 300 yards is very tough while driving over 280 yards is fairly easy, and finally, yardage has a small effect on the overall score.  

[Andrew Ross](https://github.com/44digits): [Happiness and Money](https://44digits.quarto.pub/happiness-and-money/). The happiness of a country is related to it's GDP  

[Nihal Neeraj](https://github.com/Nihal200917): [Amazon Sales Profit Prediction](https://nihal200917.github.io/Amazon-Sales-Analysis/). Online sales are the most profitable for Amazon, with a 764-unit profit increase per year, but uncertainty rates low as 153.64% and high as 307.29% due to external factors.  

[Ansh Kare](https://github.com/anshkare): [Chances of Kobe Passing the Ball](https://anshkare.github.io/kobe-project/). Kobe most always relied on his own shot-making abilities to affect the game but if they were at a disadvantage, for every point there opponent was winning by, his chances of passing increased by 3%.  

[Amogh Patil](https://github.com/AmoghPatil314): [House Price Analysis](https://slyproton.quarto.pub/house-prices-analysis/). The area of the garage (if there is one) is the biggest factor in determining the price of a house, having a coefficient of 45.  

[Nicholas Oliver Silveira Powell](https://github.com/nickospowell): [US Visas Given Out to Different Nations](https://nosp41.quarto.pub/immigration/). Mexico Is far and away the highest accepter of US visas out of every country in the world and with a 95% degree of certainty is 1.62 times more than the next largest, The Dominican Republic.  

[Madhavan Prasanna](https://github.com/Madhavan113): [Bitcoin Price Cyclicality Prediction](https://madhavan113.quarto.pub/bitcoin-price-prediction/). This project reveals Bitcoin price patterns using historical data and statistical modeling, highlighting cyclical trends.  

[Adhithan Manivassakam](https://github.com/AdhiMvm): [What factors influence Depression?](https://adhimvm.quarto.pub/understanding-depression/). The analysis indicates that age, gender, suicidal intent, and PHQ score are key predictors of depression, though individual cases may differ.  

[Cheng Ma](https://github.com/malacaus): [Oil Prices Recession](https://malacaus.quarto.pub/oil_prices_recession/). Predicting the next recession by relationship between Brent Oil Prices and US recession  

[Thomas Seoh](https://github.com/tdwseoh): [What Defines Happiness?](https://tseoh.quarto.pub/what-defines-happiness/). This project explores the most important factor that impacts happiness, which has proven to be social support.  

[Satvika Upperla](https://github.com/USATVIKA): [Longevity of Olympic Athletes](https://usatvika.github.io/Longevity-of-Olympic-Athletes/). This project explores the relation ship between the total number of medals an athlete has won and the longevity of their career at the olympics.  

[Ashitha C Kukatla](https://github.com/ashi521): [Electric Vehicle Population in Washington state](https://ashi521.quarto.pub/-electric-vehicle-population-project/). The number of electric vehicles bought in Washington state is higher counties closer to major cities.  

[Dharshan Lakshmikanthan](https://github.com/DharshanLak): [Causal Effects of Education and Experience on Global Salaries](https://dharshanlak.quarto.pub/global-salaries-on-education-and-experience/). This project analyzes the impact of education level and years of experience on global salaries, using Bayesian modeling to quantify and visualize the causal effects of these factors.  

[Ashwika Katiyar](https://github.com/ashwikakatiyar): [Conversion of Clinically Isolated Syndrome to Multiple Sclerosis](https://ashwikakatiyar.github.io/ms-conversion-factors/). Patients with a presence of bands of immunogloblins, known as Oligoclonal Bands, have about 84.5% (± 4.5%) lower odds to be diagnosed with MS.  




## July 2023

[Emmanuel Yeboah](https://github.com/kwakuemma1): [Social and Economic Factors Endangering Vulnerable Languages](https://ema-pubweb0707.quarto.pub/kanes_ds-class_degree-of-endangered-languages/). Improving agricultural opportunities in rural areas preserve vulnerable languages, but higher literacy rates and urbanization increase odds of language extinction by 20%.  

[Avery Zheng](https://github.com/averyzheng-yay): [Wimbledon 2023 Prediction](https://averyzheng-yay.quarto.pub/wimbledon2023prediction3/). Alcaraz, Medvedev, and Djokovic have the highest chances of winning the Men's draw, and Swiatek has the highest chance for Women's. 

[Daniel Cho](https://github.com/chodani): [European Soccer Wages](https://chodani.quarto.pub/european-soccer-wages/). Payroll rank within league is associated with end-of-year standings; an increase in payroll rank leads to a 0.69 increase in standing ± 0.02.  

[Alan Tao](https://github.com/alantao5056): [Carbon Dioxide and Temperature Over Time](https://alienjao.quarto.pub/carbon-dioxide/). Around 53,000 (+/- 2000) metric tons of carbon dioxide is going to be in the year 2025 and the average land temperature is going to be 20.6 C (+/- 0.6).  

[Vaangmaya Rebba](https://github.com/Vaangmaya): [Annual Income Predictions for Universities in Pennsylvania](https://vaangmaya.quarto.pub/universities-vs-annual-income/). Over 90% of the graduates make less than 100k  

[Luit Deka](https://github.com/luitdeka): [Education Expenditure on Urban and Rural Populations](https://l-deka.quarto.pub/effect-of-education-on-urban-and-rural-populations/). Every 440 billion dollars spent on education correlates to about .1% urban population growth while every 350 billion dollars of educational expenditure correlates to about .08% rural population growth.  

[Rishvanth Amsaraj](https://github.com/RishvanthAmsaraj): [Analysis of AP Exam Data](https://rishvanth-amsaraj.quarto.pub/ap-exam-data/). The findings emphasize the need for targeted efforts and interventions to support and empower minority groups, including females and black individuals, within the education system.  

[Aadhira Satheesh](https://github.com/aadhira12): [The Probability of Contracting Alzheimers Based on Different Lifestyles and Conditions](https://aadhira12.quarto.pub/alzheimers/). There are various lifestyles that you would think increase/decrease the risk of alzheimers, and this project shows you what actually can raise the risk of developing Alzheimers  

[Ethan Xiao](https://github.com/EpiCoder25): [The Effect of Engine Displacement on Fuel Economy](https://ethanx25.quarto.pub/finalproject/). The highest displacement engine has 6.375x less fuel efficiency than the lowest displacement engine.  

[Rishi Sandrana](https://github.com/RishiSandrana): [Trends in Global Education Rankings](https://rsandrana.quarto.pub/trends-in-global-education/). A country's average IQ and test scores are almost perfectly correlated (r = 0.92), but there is only a moderate correlation (r = 0.65) between either of these factors and a country's education ranking.  

[Nicholas Grant](https://github.com/nicholasgrant97): [NFL Point Spread: 1978-2013](https://nicholasgrant97.quarto.pub/nfl-spread-1978-2013/). Overall, most NFL games are decided by double digits margin of victory, with a higher average margin of victory when the point spread exceeds 7 points.  

[Sririthvik Bellala](https://github.com/srbellala): [Outcomes of Infectious Diseases from 2001-2014](https://srbellala.quarto.pub/incide-and-outcomes-of-infectious-diseases-from-2001-2014/). The total amount of people infected with E.Coli, HIV, and Malaria has decreased over time, reaching close to 0 for some years.  

[Pranav Chivukula](https://github.com/pchiaroscurist): [Chelsea's Transfer Market and its Effect on Their Season](https://pchiaroscurist.quarto.pub/chelseas-got-the-blues/). If you spend like Chelsea did in the transfer market, your season will suffer as a result.  

[Melissa Ban](https://github.com/melissaBB): [Influence of Patients' Initial Treatment Age on OrthoK Lenses Effect](https://melissabb.quarto.pub/orthok-lenses-effect/). The effect of OrthoK lenses in treating myopia is not affected by patients' age when receiving initial treatment.  


[Vibha Dara](https://github.com/vibhadara): [Diabetes Analysis](https://vibhadara.quarto.pub/diabetes2/). Females have 0.0046 times lower odds of having diabetes with a range from 0.002 to 0.010 compared to males.  

[Rajarshi Mandal](https://github.com/rajarshi-mandal): [Market Value of Fortune 500 Companies from Economic Indicators](https://rajarshi-mandal.quarto.pub/fortune-500-companies/). Companies in the Fortune 500 with 100,000 employees have an expected market value of $75 billion, plus/minus $8 billion.  

[Aryan Kancherla](https://github.com/aryan-kancherla/): [Chicago Bulls 2023-2024 Field Goal Percentage Prediction](https://aryan-kancherla21.quarto.pub/chicago-bulls-2022-2023-data/). For the 2023-2024 NBA Season, the Chicago Bulls’ predicted average field goal percentage is 48.7%.  

[Pratham Kancherla](https://github.com/prathkan03): [NBA 2023-24 Free Throw % Prediction at Each Position](https://prathkan03.quarto.pub/nba-ft-/). Each position has a predicted FT% for the NBA 2023-24 season.  

[Gaurinath Subash](https://github.com/GauripSubash): [Player Salaries vs Field Position](https://46a153568e334a09b31f51273bdb911a.app.posit.cloud/p/ec5bc91b/). On average, forwards tend to earn the most money, with an average salary of around $145,000, which is more than any other position on the field for players in the MLS League during 2007.

## February 2023

[Ava Ransbotham](https://github.com/avalxnchx): [Great British Bake Off Analysis](https://avalxnchx.quarto.pub/bake-off-the-charts/). Age does not affect how far people make it in the competition. 

[Dermot Curtin](https://github.com/fionncurtin): [The Indo-European Similarities Project](https://dfionncurtin.quarto.pub/language-project/). European branches are generally similar to each other and dissimilar to Asian branches, even though they are not always more closely related.  

[Yash Dhore](https://github.com/yash-dhore): [Analysis of Advanced Placement](https://yash-dhore.quarto.pub/advanced-placement/). Rural states with lower populations tend to have a lower number of AP Scholar Awards per capita.

[Venkat Tatituri](https://github.com/VenkatT2026): [Top 10 Youtube Channels in Subscribers](https://venkatt.quarto.pub/final-project/). These are the Top channels on Youtube! Lets see who wins the race to 10 billion  

[Matthew Ng](https://github.com/doystudent): [Coke Stocks](https://github.com/doystudent/Coke_Final_Project_draft1). Coca Cola Stocks have a good trend line and it's safe to say that soon, there may be a drop again but it will definitely rise back up in around 10-20 years.  

[Anish Bellamkonda](https://splashyzues5197.quarto.pub/indias-temperature-changes-and-effects/): [Impact of climate change on the world](https://splashyzues5197.quarto.pub/indias-temperature-changes-and-effects/). Climate change is a complex and urgent global issue that requires collective action to mitigate its impacts and prevent further damage to the planet's ecosystems and human societies.  

[Zayan Farooq](https://github.com/Zfarooq08): [How Do Position and Age Correlate With Soccer Injuries?](https://zfarooq-08.quarto.pub/final-project/about.html) Position and age in the Premier League tend to affect the type of injuries that happen to players.  

## August 2022

[Miriam Heiss](https://github.com/miriamheiss): [Classical vs Contemporary Music](https://www.miriamheiss.com/final-project/). Taylor Swift's average Song length is almost 3 minutes more than J. S. Bach's, disproving the point 'Classical Music is too long'.

[Maxwell Lu](https://github.com/chemax7): [Heart Disease: Risk Factors and Demographics](https://chemax7.github.io/Heart-Disease/). I found that men contract heart disease significantly more than women, American Indians/Alaskan Natives make up more percentage of those with heart disease than any other race.

[Krish Saluja](https://github.com/krishsal9801/): [Variables that Accurately Predict the Likelihood of a Stroke](https://krishsal9801.github.io/Final-Data-Science-Project/). Heart disease and hypertension are the most effective factors that help to accurately predict whether or not a person will suffer from a stroke.

[Sam Yeh](https://github.com/syeh5413): [Comparing Cryptopunk Data With Cryptopunk Attributes](https://github.com/syeh5413/punk-final-project). The price of Cryptopunks vary based on many attributes, but collectors buy Cryptopunks that have favorable attributes, such as lighter skin color.

[Elif Kuyuk](https://github.com/ekuyuk): [Factors that affect a Student's Academic Performance](https://ekuyuk.github.io/Student-Performance/). A higher range of scores were noted for students taking a standard lunch; female students were observed to have higher writing and reading scores.

[Krish Badri](https://github.com/krishbadri/): [Growth of Small vs Large Market-Cap Stocks](https://krishbadri.github.io/Growth-of-Small-vs-Large-Market-Cap-Stocks/). The average small market cap stock in the S&P 500 is growing at a rate much faster than the average growth of high market cap stocks at the top of the S&P 500 Weighting List.

[Rachel Heiss](https://github.com/rachelheiss): [These Prices are Defying Gravity: Broadway Trends 1985 - 2022](https://rachelheiss.github.io/broadway_project/). Today's Broadway tickets cost much more than they did in the 80s, but more people are going to shows.

[Dorothy Tang](https://github.com/Dorotho): [How the COVID-19 Pandemic Changed Emotions](https://dorotho.github.io/Final_project_2/). A survey measured people's feelings, on 7 different emotions, during the COVID-19 pandemic in the U.S.

[Varun Khedkar](https://github.com/varnkxband44): [Intelligence Quotient and Potential Indicators of Success](https://github.com/varnkxband44/cbIQpiS). Intelligence Quotient does not directly correspond with may be defined as success, however does hold a clear indirect impact on the key precursors to success.

[Jihan Bhuiyan](https://github.com/PC8923): [An Analysis of Monkeypox Demographics](https://pc8923.github.io/final-project/). While it may appear that monkeypox only impacts gay and bisexual men, this doesn't correspond with previous monkeypox outbreaks and is likely due to restrictions on testing set by governments.

[Mann Talati](https://github.com/manntalati): [NCAA Women's Volleyball Statistics](https://manntalati.github.io/NCAA_Womens_Volleyball_2012-2019/). While several teams are able to attack the ball through their attack attempts there is a very low chance of the team achieving the kill due to a block or a dig leaving the ratio of a kill to attack attempt close to 1:4 or 25% chance of achieving a kill.

[Selim Coskunuzer](https://github.com/SelimC06): [Observing NFL players Average Salary by Category over the years 2014-2020](https://selimc06.github.io/Final-Project/). NFL players salary data over a few years to see if it has differed

## June 2022

[Suvan Dommeti](https://github.com/SuvanD0): [Presence of Polarzing Words in Australian Media](https://suvand0.github.io/Polarizing-words-in-media-over-time/). Does Australian media excessively use the word "riot" over "protest" to convey a biased message?

[Jackson Roe](https://github.com/jacksonrroe): [March Madness: How to Pick a Perfect Bracket](https://jacksonrroe.github.io/march_madness_analysis/). Analysis of the trends in every March Madness bracket since the 1985 expansion to 64 teams.

[Farhan Sadeek](https://github.com/FarhanSadeek21): [Analysis of World Population](https://farhansadeek21.github.io/population_analysis/). Life Index is proportional to the Per Capita GDP of a country.

[Allison Bubar](https://github.com/allisonbubar): [Newton North High School Basketball Evaluation](https://github.com/allisonbubar/distill-tutorial/blob/main/README.md). The NNHS basketball teams success was determined by FG% and defensive success.

[Alex Kuai](https://github.com/AlexKuaiR): [Microchip Market](https://alexkuair.github.io/Microchip-Market/). Dramatic increase in microchip market demand in the Asia Pacific region

[Ethan Hu](https://github.com/ethanhu89): [Breakdown of the S&P 500](https://ethanhu89.github.io/Final-Project/). Shows the basic trends that are seen in the top 500 public companies in the US.

[Nathan Rothschild](https://github.com/NathanRothschild): [Comparison of Three 33 y/o Professional Tennis Players' Effectiveness](https://nathanrothschild.github.io/tenniswebsite/). Professional players of the same age, career length, and similar career success had vastly different effectiveness trajectories during their career.

[Shivangi Nadkar](https://github.com/ShivangiNadkar): [COVID deaths by race and education level](https://shivanginadkar.github.io/COVID_deaths_project/). Graphs that display COVID-19 deaths and are faceted by race and education level.

[Henry Sippel](https://github.com/sipphen): [Fish Stocking Data in Lake Michigan by Species](https://sipphen.github.io/fish-stocking/). Movement of fish stocking in Lake Michigan.

[Pooja Kawatkar](https://github.com/pkawatkar): [Analysis of Superbowl Statistics](https://pkawatkar.github.io/football_statistics/). In 1990, the San Francisco 49ers defeated the Denver Broncos by 45 points, the greatest point difference in Superbowl history

[Samruddhi Naik](https://github.com/samnaik10): [Wages by Gender and Occupation](https://samnaik10.github.io/wages-by-gender/). The biggest wage gap is in the financial industry where men earn around \$45,000 more than women do.

[Awais Choudhary](https://github.com/awaischoudhary): [Traffic Violations](https://awaischoudhary.github.io/Traffic-Violations/). What a driver should avoid on the road; an examination of traffic infraction records.

[Sai Gottemukkula](https://github.com/SaiGottemukkula): [An Exploration of COVID-19](https://saigottemukkula.github.io/FinalProject/). Graphs that look at some under-explored information of the pandemic.

[Akhilesh Sangaraju](https://github.com/AkhileshSangaraju): [Cars - CO2 Emissions and Efficiency](https://akhileshsangaraju.github.io/CO2-Emissions-and-Effciency-of-Cars/). When buying an electric car, you can be confident that you are making the eco-friendly decision, and that it will statisfy all of your needs.

[Amisha Jain](https://github.com/amishaj08): [Karate Statistics Around the World](https://amishaj08.github.io/new_final/). These graphs analyze how various countries are impacted by Martial Arts.

[Nathan Nambiar](https://github.com/nathannambiar): [Progression of Agent Pick Rates in Valorant](https://nathannambiar.github.io/final-project/). The change in agent pick rates throughout Valorant history.

[Hannah Adams](https://github.com/hannah-adams): [Per capita CO2 emissions](https://hannah-adams.github.io/kanes-camp-final-project/). Shows trends in per capita CO2 emissions by country, which could inform equitable environmental policy.

[Katie Zhong](https://github.com/katie-zhong): [Factors of Success in WEBTOON Originals](https://katie-zhong.github.io/webtoon-originals-analysis/). Viewer ratings and subscriber counts prove that Romance and Fantasy Originals are the most popular.

[Noel Jung](https://github.com/NoelJung): [Temperature and Vector Borne Diseases](https://github.com/NoelJung/Temperature-and-Vector-Diseases). Do changes in temperature affect the number of cases of West Nile and Lyme disease?

[Lucas Cao](https://github.com/ExceedEvergreen/): [Number of Billionaires over Years](https://rpubs.com/Exceed_Lucas/billionaire). The number of billionaires has been increasing rapidly every year since 2000.

[Andrew Zhuo](https://github.com/Stackfish5): [Chess Openings](https://github.com/Stackfish5/Final-Project). Analyzing the most commonly used chess openings by 5 top chess Grandmasters.

[Austin Zhuang](https://github.com/austzhua): [Adult Mental Health in the USA](https://github.com/austzhua/final-project). The project analyzes of how financial factors affect access to mental health

[Suvan Chatakondu](https://github.com/suvancha9866): [Movies 2021 Analysis](https://suvancha9866.github.io/movies_2021_project_2/). The factors that made movies in 2021 successful and special.

## June 2021

[Sophia Zhu](http://github.com/zhusophia): [BREAKING NEWS: FBI Says They Found 'Man Child' In The Woods!](https://zhusophia.github.io/testingdolalrsign/) An analysis of the length and wording of 2018 fake news articles titles.

[Nuo Wen Lei](https://github.com/NuoWenLei): [PAC Influence on US Politics](https://nuowenlei.github.io/pac-influence/). Trend of foreign donations seems to parallel party representation in US congress.

[Kevin Xu](https://github.com/K3vX21): [ATP Tour Analysis Over Time](https://k3vx21.github.io/atp-analysis/). The game of tennis on the ATP Tour has shifted tactically and demographically since its conception.

[Stefan Arroyo-Cottier](https://github.com/StefanA-C/): [The Time Hass Come](https://stefana-c.github.io/final_project_website/). Avocado consumption and prices in the United States over time.

[Osaretin Lawani](https://github.com/oplawani56): [An Analysis of the Causes Singapore's Aging Population](https://oplawani56.github.io/Singapore-Project/). This is an investigation of the relationship between Singapore's aging population and the nation-state's declining birth rates

[Dhruv Syngol](https://github.com/dsy5): [World Happiness Report Data Analysis and Visualizations](https://dsy5.github.io/World-Happiness-Data-Analysis-and-Visualizations/). Data from the World Happiness Report over the years reveals interesting trends in a variety of factors, from GDP per Capita to the Freedom to Make Life Choices.

[Abhay Paidipalli](https://github.com/abhay1105): [The Evolution of Basketball](https://abhay1105.github.io/The-Evolution-of-Basketball/). An analysis of some of the most noticeable trends in the history of basketball.

[Marco Tchernychev](https://github.com/Marco-Tchernychev): [20/21 EPL Data Visualizations](https://marco-tchernychev.github.io/EPL_20_21_Final/). This project examines the correlation between age and goals, as well as nationality and passing.

[Max Xu](https://github.com/maxzixiaoxu): [Covid 19 Around the World](https://maxzixiaoxu.github.io/Covid_project/). Examining Covid 19 cases and trends among the continents.

[Ajay Malik](https://github.com/AM-lmn): [High School Performance and Future Salary, by College](https://am-lmn.github.io/high-school-salaries/). The more students of a university who were at the top of their high school class, the more salary these students will make.

[Shreeram Patkar](https://github.com/s-patkar): [Covid-19 Socio-Economic Causal Analysis](https://spatkar.shinyapps.io/Covid-Shiny/). Comparing different socio-economic metrics to Covid death and infection rates

[Z Schwab](https://github.com/z-schwab): [GDP and Wealth Distribution: Not a Uniform Picture](https://github.com/z-schwab/final-project-gdp-inequality). GDP is an inaccurate indicator of quality of life because it doesn't factor in income inequality.

[Andre Arroyo-Cottier](https://github.com/andreread): [Covid Cases and Vaccination Rates in the US](https://andreread.github.io/Final_R_Website/). Graphs that show the effectiveness of vaccinations in the USA.

[Daniel Chen](https://github.com/Danielc1218): [Population and Crime rate in the US](https://danielc1218.github.io/Data_Camp_Final_Project/). Population and crime rate have no correlation in the US.

[Tejas Mundhe](https://github.com/TejasMundhe): [United States Covid-19 Death Toll by State](https://tejasmundhe.github.io/Covid_Deaths-Website/). Are more populated states impacted by the Covid-19 pandemic more than less populated ones?

[Matthew Ru](https://github.com/matthewru): [An Analysis of Pro Tennis Players](https://matthewru.github.io/data-camp-final-project/). An arrangement of graphs to show the relationship between height, weight, birth month, and country of origin in the tennis pro-scene.

[Ronit Anandani](https://github.com/anandani4136): [COVID-19 and its Impact on Sectors of the Stock Market](https://anandani4136.github.io/Stock-Market-Analysis/). Visualizing the effect of COVID-19 pandemic on different stock market sectors.

[Frank Li](https://github.com/lifrank1): [Chance of Automation Replacement of Various Occupations](https://lifrank1.github.io/JobRiskFromAutomation/). Exploring the likelihood of a variety of occupations being replaced by machine labor.

[Zuhair Usmani](https://github.com/zuhair-school): [Movie Genres and if Producers are using the same genres](https://zuhair-school.github.io/movie-project/). Gathering movie genres and analyzing if producers are using the same genres.

[Bryan Li](https://github.com/libryan261): [Covid-19 Effect on Student Mental Health and Behavorial Change](https://github.com/libryan261/Actual-Final-Project). Analyzing the effects of the pandemic on the mental and physical health of students and adults.

[Mahima Malhotra](https://github.com/mmal1524): [Diabetes Prevalence by State](https://mmal1524.github.io/DSB_final/). A comparison of the prevalence of diabetes among adults by state to rates of depression amongst adults with diabetes and mortality rates.

[Yuhan Wu](https://github.com/UhanWu): [Housing Fluctuation Using Case-Shiller Index](https://uhanwu.github.io/HousingPrep/). The two key factors that influenced the housing price are income and housing supply; population matters little.

[Nabiha Rabbani](https://github.com/nabihar): [Sci-Fi and Techno Orientalism](https://nabihar.github.io/FinalProjectWebsite/). Measuring interest in science fiction movies over time and comparing that interest to economic success in East Asian countries.

[Emmanuel Buabeng](https://github.com/EmmanB1): [Average Salary Per Department in Chicago](https://emmanb1.github.io/RFinalProject/). An analysis of spending across government departments in the city of Chicago.

[Fahim Ahmed](https://github.com/fahimahmed0x): [Investment Analysis of Exchange Traded Funds (ETF)](https://fahimahmed0x.github.io/funds/). What types of ETFs would have made you the most returns if you invested in them last year?

[Isaac Frank](https://github.com/isaac-w18): [Anxiety and the Need for Research](https://anxiety-research.netlify.app/anixety_data.html). Examining the correlation between pharmaceutical spending and anxiety.

[Anmay Gupta](thttps://github.com/AnmayG): [Effect of Various Factors on 3D Print Strength](https://anmayg.github.io/3D_Print/). 3D prints can be strengthened by changing a variety of factors.

[Srihith Garlapati](https://github.com/srihithg): [Goverment Department Earnings by Region](https://srihithg.github.io/finalProject/). This is an investigation of the highest earning departments on average per each state in each region in the US.

[Tom Pan](https://github.com/TomPn): [COVID-19 Cases/Vaccinations Analysis](https://tompn.github.io/Cases-Vaccinations-Analysis/). Analyzing cases and vaccination progress in China, Canada, United States, and United Kingdom.

[George Pentchev](https://github.com/1pentchevgeo/): [Course Enrollment in Secondary Schools](https://1pentchevgeo.github.io/final-project/). Ranking secondary school courses by enrollment and examining the growth of the most popular courses.

[Gabriel You](https://github.com/GabeYou): [Sinoalice Power vs Cost Analysis](https://gabeyou.github.io/Sinoalice-Final-Project/). Looking at Sinoalice Weapons and comparing weapon total power to cost to see the correlation between them.

[Joseph Jeiwan Kim](https://github.com/josephwanjei): [Change In Sea Level](https://josephwanjei.github.io/SeaLevelRise/). An examination of climate changes impact on the global sea level.

[Varun Mittal](https://github.com/Varun121322): [Impact of Covid On Home Court Advantage in the NFL and NBA](https://varun121322.github.io/Home-Field-Advantage-Across-Sports/). Examining how much home court/field advantage was affected by Covid-19 by measuring the amount of times that home team won and other stats.

[Shyam Sai Bethina](https://github.com/Shyamsaibethina): [Motor Vehicle deaths by Age and Year](https://shyamsaibethina.github.io/Alchohol-Related-Mothor-Deaths/). Is the message "Don't drink and Drive" still prevalent in older people?

[Oliver Altindag](https://github.com/OliverAltindag): [Liverpool Football Clubs Best Eleven](https://oliveraltindag.github.io/Liverpool-FC-Best-11/). This is an inquiry into the statistics of Liverpool FC and the best possible Eleven the club could field in future games.

[Daniel Wang](https://github.com/DanWang725): [Effects of Covid-19 on Student's Educational Stress](https://danwang725.github.io/EducationStress/). Examination of the stress levels experienced by students before and during Covid-19.

[Arghayan Jeiyasarangkan](https://github.com/JArghayan): [How The Overall Gold Difference Changes Throughout Professional League of Legends Games](https://jarghayan.github.io/Final-Project/). Examining the relationship between gold difference and game duration in professional League of Legends matches.

[Arjun Velayutham](https://github.com/ArjunVelayutham): [Earnings vs Inflation](https://github.com/ArjunVelayutham/Johnson-Johnson-Earnings). Have the increase in a companies earnings outpaced the inflation margin.


[Shreya Sree Morishetty](https://github.com/shreyamori): [Undergraduate Engineering Enrollment by Demographics](https://shreyamori.github.io/Actual-Final-Project/). Exploring if the demographics have changed through the years as enrollment in engineering programs have risen.

[Stephanie Saab](https://github.com/stephaniesaab): [These Boots are made for Shopping](https://stephaniesaab.github.io/Shoe_shopping/). A comparison of men and women's shoe shopping tendencies shows that women spend more money while men are fond of a sale.

[Kyle Sabo](https://github.com/sabokyle12): [How Speed Affects Offensive Ability in Baseball](https://sabokyle12.github.io/baseball-project/). Determining the extent that speed enables players to get more hits.

[Varun Dommeti](https://github.com/d-varun): [Prevalent Emotions in Mainstream Music, by Decade](https://d-varun.github.io/final-bootcamp-project/). Exploration of emotions in the billboard top 100, sorted by decade.

[Soham Gunturu](https://github.com/SohamGunturu): [Mortality rate of babies under different variables](https://github.com/SohamGunturu/final-project). Relationship between mortality rate of children under 5 per 1,000 live births and year, country, and economic class.

[Felix Cai](https://github.com/FelixCai525): [Relationship Between GDP per Capita and Percentage of Population with a Confirmed Case of COVID-19](https://felixcai525.github.io/FP/). Exploring the relationship between GDP per capita and percentage of population with a confirmed case of COVID-19.

[Heather Li](https://github.com/heatherli12): [An Overview of Toronto Shelter Data in 2020](https://heatherli12.github.io/toronto-shelter-data/). Mapping the occupancy percentage of Toronto shelters during 2020.
