---
title: "Schedule"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Classes run from 8:00 to 9:00 PM EDT on Mondays, Wednesdays and Thursdays.

Key resources: [*R for Data Science (2e)*](https://r4ds.hadley.nz/) by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund, [*Preceptor's Primer for Bayesian Data Science*](https://ppbds.github.io/primer/) by David Kane, [*Analyzing US Census Data: Methods, Maps, and Models in R*](https://walker-data.com/census-r/) by Kyle Walker, along with their [their](https://ppbds.github.io/r4ds.tutorials/) [associated](https://ppbds.github.io/primer.tutorials/) [tutorials](https://ppbds.github.io/tidycensus.tutorials/). Homework should be completed before the class meeting for which it is assigned.

See the home pages for the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/), [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/), and [**tidycensus.tutorials**](https://ppbds.github.io/tidycensus.tutorials/) for installation instructions.

**Always reinstall the relevant package before starting a new tutorial.** We are always fixing mistakes. You want to use the latest version.

Completed tutorials are submitted via [this Google form](https://forms.gle/ScrSYjb6pYPbtvNj7). If you do not complete the tutorials on time, you will be removed from the class. Send in your tutorial answers saved in *html* format. Please try to ensure that the name of the file is the default name, like `getting-started_answers.html`. Avoid using the name which will be assigned to the file if you download the same answers twice (or more), stuff like `getting-started_answers (2).html`. You can just change the name of the file by hand if this happens.


# Registration

To register for the class and reserve your spot, please read [Getting Started](https://ppbds.github.io/primer/getting-started.html) and follow all the associated instructions. Complete the "Getting Started with Tutorials" tutorial from the [**tutorial.helpers**](https://ppbds.github.io/tutorial.helpers/) package. Submit your answers, as an html file, via [this Google form](https://forms.gle/ScrSYjb6pYPbtvNj7).

# Week 1: Data: June 3

Looking at the data is the first step in data science. Note that Monday's homework must be completed before Monday's class. I ensure this by only sending the Zoom link for class to students who submitted the homework.

## Monday 

* Read the Introduction from [*R for Data Science (2e)*](https://r4ds.hadley.nz/). 

* From the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Introduction" tutorial. Submit your answers via the usual [Google form](https://forms.gle/ScrSYjb6pYPbtvNj7). 

## Wednesday 

* Read Chapters 1 and 2 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/). 

* From the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete two tutorials: "Data Visualization" and "RStudio and Code." The second of these is the most important. Submit your answers via the usual [Google form](https://forms.gle/ScrSYjb6pYPbtvNj7). 

## Thursday 

* Read Chapters 3 and 4 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/). 

* From the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the associated tutorials: "Data Transformation" and "RStudio and Github." The most important of these is "RStudio and Github."

**Reminder**: All work must be completed before class. Failure to submit your tutorial answers will result in you being removed from the course. It is not fair to your fellow students, with whom you will be working in small groups, for you to not be prepared for class.

# Week 2: Models: June 10

Now that we know how to visualize data that is already clean, we need to learn how to clean up messy data. 

## Monday 

* Read Chapters 5, 6, and 7 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/), and from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the tutorials associated with the readings: "Data Tidying," "Terminal," and "Data Import."   
 

## Wednesday 

* Read Chapters 8, 9 and 10 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/), and from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the tutorials associated with the readings: "Getting Help," "Layers," and "Exploratory Data Analysis." 


## Thursday

**The tidycenus.tutorials are not yet complete. Don't start them yet.**

* Read chapter 11 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/), and from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the associated tutorial: "Communication." 

* Read chapters 1 and 2 from from [*Analyzing US Census Data: Methods, Maps, and Models in R*](https://walker-data.com/census-r/index.html) by Kyle Walker. The U.S. Census is a great source of data for your projects.


* From the [**tidycensus.tutorials**](https://ppbds.github.io/tidycensus.tutorials/) package, complete the "An introduction to tidycensus" tutorial.  



# Week 3: Inference: June 17


## Monday 

Read chapters 12, 28 and 29 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Logical vectors" and "Quarto" tutorials.



## Wednesday 

* Read chapters 13 and 14 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the  "Numbers" and "Strings" tutorials. 

* Read the [Style Guide](https://ppbds.github.io/primer/style-guide.html). 

* Determine the data source you will use for your final project. Don't come to class without one!

## Thursday 

* Read chapters 15 and 16 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Regular expressions" and "Factors" tutorials. 




# Week 4: Wisdom: June 24

The main focus on the 4th week is individual presentations of your Data Project. Do you love soccer or wine or NYC politics? The Data Project provides you with an opportunity to study that topic in depth. Your Data Project will be, for most of you, the first item in your professional portfolio, something so impressive that you will be eager to show it to graduate schools or potential employers.

<!-- DK: Add back in the final project tutorial. -->

## Monday

* Read chapter 17 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Dates and times" tutorial.

## Wednesday 

* Read chapter 18 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Missing values" tutorial.

* Practice presentations and feedback. You must have your presentation ready to go! 

## Thursday 

* Data Project presentations. You must invite someone, and bcc your TF when you do so. The presentations are public.


**TWO WEEK VACATION: July 1 through July 14**

**The primer.tutorials are not yet complete. Don't start them yet.**

# Week 5: Justice: July 15

## Monday

* Read [Chapter 1 Rubin Causal Model](https://ppbds.github.io/primer/rubin-causal-model.html), focusing on sections 1.1, 1.2 and 1.4, and [Chapter 2 Probability](https://ppbds.github.io/primer/probability.html), focusing on sections 2.1, 2.2, 2.7, and 2.8.  

* From the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package, complete "Rubin Causal Model - Overview" and "Probability - Overview" tutorials.

* Read chapter 19 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Joins" tutorial.

## Wednesday

* Read [Chapter 3: Sampling](https://ppbds.github.io/primer/sampling.html) and, from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package, complete the "Sampling - Overview" tutorial.

* Read chapter 20 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Spreadsheets" tutorial.


## Thursday

* Read [Key Concepts](https://ppbds.github.io/primer/glossary.html).

* Read [Chapter 4: Models](https://ppbds.github.io/primer/models.html) and, from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package, complete the "Models - Overview" tutorial.

* Read chapter 21 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Databases" tutorial.


# Week 6: Courage: July 22

## Monday

* Read [Chapter 5: Two Parameters](https://ppbds.github.io/primer/two-parameters.html) and, from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package, complete the "Two Parameters - Overview" tutorial.

* Read chapter 22 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Arrow" tutorial. 

## Wednesday

* Read [Chapter 6: Three Parameters: Causal](https://ppbds.github.io/primer/three-parameters-causal.html) and, from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package, complete the "Three Parameters: Causal - Overview" tutorial.

* Read chapter 23 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Hierarchical data" tutorial. 

## Thursday

* Read [Chapter 7: Mechanics](https://ppbds.github.io/primer/mechanics.html) and, from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package, complete the "Mechanics - Overview" tutorial.

* Read chapter 24 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Web scraping" tutorial. 

# Week 7: Temperance: July 29

## Monday

* Read [Chapter 8: Four Parameters: Categorical](https://ppbds.github.io/primer/four-parameters-categorical.html) and, from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package, complete the "Four Parameters: Categorical - Overview" tutorial.

* Read chapter 25 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Functions" tutorial. 

## Wednesday

* Read [Chapter 9: Five Parameters](https://ppbds.github.io/primer/five-parameters.html) and, from the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package, complete the "Five Parameters - Overview" tutorial.

* Read chapter 26 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "Iteration" tutorial. 

## Thursday

* Read [Chapter 10: N Parameters](https://ppbds.github.io/primer/five-parameters.html) and, from the [**primer.tutorials**](https://ppbds.github.io/primer/n-parameters.html) package, complete the "N Parameters - Overview" tutorial.

* Read chapter 27 from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) and, from the [**r4ds.tutorials**](https://ppbds.github.io/r4ds.tutorials/) package, complete the "A field guide to base R" tutorial. 


# Week 8: Projects: August 5

The last week will consist of projects that the students will make. 


## Monday 

* From the [**primer.tutorials**](https://ppbds.github.io/primer.tutorials/) package, complete "Final Project" tutorial before class, or you will be removed the course. There are no extensions for this assignment.

* You must have a draft of your final project ready to go, including a Quarto website and your four sentence introduction. 


## Wednesday 

* Practice presentations and feedback. You must have your presentation ready to go! 

## Thursday 

* Final project presentations. You must invite someone, and bcc your TF when you do so.




