---
title: "Day 8"
---

Last class, we built a project. But it went fast! Students missed lots of things! Let's do it again, going quickly over some items while still spending time on important concepts. Key learning object is moving stuff from index.qmd to a script and the use of saved objects.

## Scene 1: Make/Publish Website

Follow the same steps as in the Quarto Websites tutorial to build a new website from scratch.

* `File -> New Project... -> New Directory -> Quarto Website`

* Name the 'project-2`. `Create Project`

* Take a tour of some of the files in the File pane. Note that there is nothing about Git/Github because we have delayed that part. Note that 

* Edit the `title` in `_quarto.yml` to be something like "Cool Project Name". 

* Clean junk from `about.qmd` and then add a link to the bootcamp.

* `quarto publish` the project. Note the need to hit return twice. 

* Take a look at your cool website!

Send to rooms.

## Scene 3: Git/Github

Time to save our work in case our computer blows up.

* Run: `usethis::use_git()`. Answer No to the first question and Yes to the second.

* Check out all the new files! Try `git log`. Still, haven't done anything with Github yet.

* Edit the `.gitignore` to add `*Rproj`. Commit all files. Note how you can't push yet. No Github!

* Run: `usethis::use_github()`. Does this change anything in our directory? Not sure! Don't see any files changed. Run `git log` to check.

* Push all files.

## Scene 4: Add Map

* Edit the `index.qmd`. Discuss why it is named "index." Copy the Hennepin dot density example:

https://walker-data.com/census-r/mapping-census-data-with-r.html#dot-density-maps

Note that you need to download the data in an earlier example.


Should work out of the box. Render. `quarto publish`. Now we are cooking with gas!

* Go to your rooms and choose a different state/county. What pops up? What aspects should you clean up, like messages and code echos?

## Scene 5: Separate out data download

* Don't want to download the data each time you render the home page. What a waste! Instead, move the data download to an R script and do it once. 

* Script must be self-containted. Must including libraries. Must save out the final tibble as an rds object.

* Edit the index.qmd to read in that rds file. No downloads every time.

## Scene 5: Separate out image creation



## Scene 6: Clean Map

* Show how to clean up the appearance of the website with, for example, `echo: false` and `message: false`.

* Publish final version. Place link to website into #class-work.






