---
title: "Day 1"
author: "David Kane"
---


## Goal

Explore the connectedness data from the primer.data package. Answer some questions. Students will have completed the Introduction tutorial, so they have been exposed to both ggplot2 and to the pipe.

Lesson from last time: Less time in the breakout rooms in the first few sessions. More time once you start asking R questions.

## Session 1

Go to the Preceptor's Notes. Talk through the first few items. Finish with room assignments. Send them to those rooms to meet each other. Each person gives one sentence about themselves. 

## Session 2

Cold call to tell me one thing about one student in the breakout room

Review breakout room behavior. One person always sharing, and then doing nothing but what they are told. Another person driving, telling the screen-sharer what to do.

Go through items 2 (useful links) and 3 (install tutorial.helpers). 

Give a quick tour of RStudio. (Make sure that you are starting your session in an empty project and with no code visible.) Show the three *panes*: Console, Environment and Output. Mention the different *tabs*. 

Type 2 + 2. 

Tell them to update tutorial.helpers

```
remotes::install_github("PPBDS/tutorial.helpers")
```

Send them to breakout rooms to do the same.

But do this together! One person shares their screen. One other person drives.

There may be problems, especially for students who are using a different computer from the one they used when they did the Getting Started chapter.

## Session 3

Review items 4 (Ulysses), 5 (Discord) and 6 (chatGPT).

Show them library(tidyverse). Discuss those weird messages. Explain the concept of the Tidyverse. Mention that we load up this package (i.e., this collection of packages) whenever we use R.

Show them library(primer.data). 

Make sure all students have primer.data installed. They certainly need this for the next class. Show page in Getting Started for doing so.

Pull up chatGPT. Require them to sign up for one of the services. No need to pay! Free service is fine. Mention that I use Claude. Show the tab for Claude.

Send them to breakout rooms to do the same. Tell them to help (by having them share their screen) whomever is having the most problems.

Ask chatGPT something goofy. Like write an haiku about what a cool language R is.

## Session 4

Cold call for the goofy thing.

Type connectedness. Run ?connectedness. 

See Preceptor Notes for links.

Explain the need to reinstall r4ds.tutorials each week-end. We are always fixing bugs!

remotes::install_github("PPBDS/r4ds.tutorials")

Go to breakout rooms. Reinstall r4ds.tutorials. Switch the screen-sharer and driver. Then, answer this question:

How should we explore this data? Let's ask chatGPT: What functions are useful for exploring a new tibble in R?


## Session 5

Call on someone at random to tell me about interesting functions.

What is the third biggest, by population, county in the US?

Go to breakout rooms, ask chatGPT, and follow its advice.

## Session 6

Call on someone at random to tell me what to code.

What are the counties with the lowest connectedness? Why is that? Maybe ask chatGPT.


## Extra Questions

If a group is too far ahead, ask them to create a graphic which makes a histogram of county populations. Or a scatterplot of population versus connectedness.

