---
title: "Day 10"
---

## Goal

Set the stage for a successful Demo Day.

Try the "Broadcast Voice" to chat room button. Confirm that it will be usable for Demo Day.

## TF Advice

Goal is to help students have a successful project. We do this by both helping them directly but also by highlighting cool stuff in other students' projects. After all, if student A is making interesting use of animation, there is still time for student B to add animation to his project. 

The culture of data science is one that encourages inspiration from other data scientists!

Make sure to point out errors in following the Style Guide. Tell students to read it!

Tell students to write code comments. In fact, spend 10 minutes during your breakout room having all students add comments. And then walk through those comments, giving feedback. Key paragraph: https://ppbds.github.io/primer/style-guide.html#comments

Discuss students' 4 sentence summaries. Focus on the takeaway point. What is the one sentence which they hope viewers will walk away with?

Review the submissions to the spreadsheet. Several are not following the instructions. Ensure that they do. 


## Session 1

Go to breakout rooms. One student volunteers to share their project. She shares her screen. She reads her paragraph. (Presumably, she hasn't memorized it yet. For Demo Day, it should be memorized.) She explains the key plot in no more than a paragraph/

And that is all! We don't let her prattle on. We take control. At that point, you share your screen. You open her project. You give a guided tour, including your thoughts. You highlight any place in which she failed to follow the instructions.

Obviously, you have more than one room. So, you might visit both rooms quickly at the beginning. You stay in one, and encourage students to offer comments in the second. Then you switch.

## Session 2

Go to breakout rooms and each person in the group sends the invitation email to someone, cc'ing Tejas and your TF. Once everyone has done this, another person gives a tour of their project.


## Session 3

Tell students to confirm/deny whether or not they are attending demo day. Point them to the room assignment spreadsheet. Try to confirm everything. Make note of students that are still problematic. Email them. Move them to the last rooms in your grouping. That is the easiest place from which to just delete them.

Make the edits which you can right after class. Email Tejas to discuss problem cases. By default, just kick people out. If they did not fill out the data project sheet then, by default, they are out. They can still stay in the course.

## Session 4

Go to breakout rooms. Everyone pulls up their code. Everyone starts adding comments. You rotate who is sharing their screen. Someone always is. But everyone is adding their own comments. Highlight the paragraphs in the Style Guide which describes good comments.

## Session 5

Later sessions just feature more students showing their work, as in session 1. With luck, everyone will get a chance to go.

