---
title: "Day 9"
execute: 
  echo: false
---

Make another website. Need to think more about what the topics should be, the better to push students toward interesting projects. What other topic besides tidycensus and tidytext would be good for this purpose? In any event, let's experiment with a different approach today. Working with a random student's data.

## Session 1

Start up a data science project! That means, a new Github repo, connected to a new RStudio project on your computer, with appropriate changes made in your .gitignore and everything pushed to Github. 

Have someone in your group volunteer to have their data used. (Must be relatively simple data.) Everyone downloads their own copy. This is what I am using (thanks Areeb!)

```
https://www.kaggle.com/datasets/jainaru/ranking-sports-by-skill-requirement
```

Make sure everyone in your group is set up. 

Extra time? Take a tour through the data associated with one person's project. (This is one time in which we allow the person who is sharing their screen to also do some talking.)


## Session 2

Cold call: Tell me about your peer's project? Or your project!

In the project, create a Quarto website. From the Terminal:

quarto create project website .

Remind yourself, from the tutorial, what the files mean/do. Preview the website:

quarto preview

Make sure this works for everyone in your group. Extra time? Student 2 gives a tour of her data.

Start editing the index.qmd.

## Session 3

Cold call: Tell me about another project in your group.

Edit the index.qmd to load some libraries and read in the data. Looks at the data! Poke around! Start thinking about a plot.

## Session 4

Cold call: How did your group do?

Ask ChatGPT:

```
I have a tibble x, which looks like this:

x

How can I make a nice graphic?
```

Use whatever text you like. If the plot doesn't look good. Tell AI what to change.

Once the plot starts looking good, consider organizing things a bit better, as we did in the Quarto Websites tutorial. Perhaps clean_data.R script. Perhaps a make_graphic.R script. Maybe index.qmd only loads an image.

Clean up about.qmd.


## Session 5

Publish your website with:

quarto publish quarto-pub

Make sure this works for everyone in your room.

## Session 6

Clean up your website.

0) Put your download data in a script and just do it once.

1) Make your plot nicer. There is obviously a lot that one might do.

2) Clean up the about.qmd, the title, and so on.

