---
title: "Day 12"
---

## Next Time

This will need to be adjusted, given whatever changes we make in days 10 and 11. Basic message is that we need to devote lots of time to the Cardinal Virtues.

Questions: What will be the attitude toward immigration, measured on the 3 to 15 scale, of a Parisian after they hear two Arabic speakers walking down the street? What about the average Parisian? What about the 90th percentile of Parisians?


## Scene 1

Start a data science project. Repo -> Project -> Quarto. Load up `trains` tibble form the **primer.data** package. Explore the data, especially `treatment`, and `att_end`.


## Scene 2

In your room, apply the Cardinal Virtue of Wisdom to this problem. First, describe the Preceptor Table which would allow us to answer the question. Is this a causal or predictive model? What are the units, outcomes, and covariates? (There are no treatments because this is not a causal model.) Second, explore the data we have. (But we already did this.) Third, examine the assumption of validity. Is the "treatment," which is really a covariate since everyone gets it, in the Preceptor Table close enough to the "treatment" in our data that we can consider both to have come out of the same population?

## Scene 3

Justice. Describe the Population Table. We can only create this object because the assumption of validity allows us to assume that there is an underlying population from which our data and the Preceptor Table might be drawn. Go through the next three assumptions: stability, representativeness and unconfoundedness. For each, write down one reason why that assumption might *not* hold in this case. How would those failure impact the results?

Last step for Justice is to decide the mathematical form for our model. The 


## Scene 4

Courage. We have not, yet, used R to create a model. That starts next week. That process will look like this:

```{r}
librar

fit_1 <- stan_glm(att_end ~ treatment,
                  data = trains,
                  refresh = 0,
                  seed = 10)
```

But, again, that is too much for today. If you have not seen code like this, it is because you did not complete today's tutorial assignment!


## Scene 5

Temperance. How do we use that model to make a forecast? With humility!  But, the world is less certain that the naive use of that posterior would suggest because our assumptions are never perfect.







