---
title: "Day 6"
---

## Goal

Work with and understand Massachusetts Census tracks data. Make a simpler plot. This will become Day 5 next time, although with NYC data probably.

## Session 1

You are data scientists! How do you start a project? Github -> RStudio Project -> Download the data into the `data` directory -> Start a Quarto document -> Load the data.

Of course, you have done this several times already. But we need to practice this procedure a dozen more times before the class is over. Practice makes perfect.

## Session 2

Cold call: Walk me through the initial stages.

## Session 3

Cold call: Finish up the initial steps.

Did you edit the .gitignore? Did you push to Github? 

Make sure that everyone in your group has done this.

## Session 4

Let's take a closer look at the data. (We should have done this yesterday.)

What are some commands to look at a new data set? How about print(), summary(), slice_sample(n = 5), tail()? Maybe skimr::skim?

What about doing these calculations for each group separately?

What do the words in tract mean? How many counties are there in Massachusetts? Do we have data from all of them?

## Session 5

Cold call: What did you group do?

Make a plot. Don't make it the same as yesterday! Do something different. Maybe a box-plot by race? Maybe a plot which shows a bar plot with the standard deviation for each race? Maybe a histogram of med_income, faceted by race? 

## Session 6

Cold call: How are things going?

## Session 7

Publish the plot to Rpubs. Looks OK. But it is a little ugly to have the title and, maybe the author, edit the YAML to remove. Re-publish. Add link to class-work.


